import RestaurentCard from "../components/RestaurentCard";

const resList = [
  {
    type: "restaurant",
    data: {
      id: "101",
      name: "KFC",
      imageUrl: "https://upload.wikimedia.org/wikipedia/en/b/bf/KFC_logo.svg",
      cuisines: ["Burgers", "Biryani", "Fast Food"],
      avgRating: "4.2",
      costForTwo: 40000,
      deliveryTime: 36,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "102",
      name: "McDonald's",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/36/McDonald%27s_Golden_Arches.svg",
      cuisines: ["Burgers", "Beverages", "Desserts"],
      avgRating: "4.0",
      costForTwo: 30000,
      deliveryTime: 28,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "103",
      name: "Pizza Hut",
      imageUrl: "https://upload.wikimedia.org/wikipedia/en/d/d2/Pizza_Hut_logo.svg",
      cuisines: ["Pizzas", "Pasta", "Italian"],
      avgRating: "3.8",
      costForTwo: 35000,
      deliveryTime: 30,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "104",
      name: "Domino's Pizza",
      imageUrl: "https://upload.wikimedia.org/wikipedia/en/8/8b/Dominospizza_logo.svg",
      cuisines: ["Pizzas", "Burgers", "Sides"],
      avgRating: "4.1",
      costForTwo: 20000,
      deliveryTime: 25,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "105",
      name: "Subway",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Subway_2016_logo.svg",
      cuisines: ["Healthy Food", "Salads", "Sandwiches"],
      avgRating: "3.9",
      costForTwo: 25000,
      deliveryTime: 22,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "106",
      name: "Burger King",
      imageUrl: "https://upload.wikimedia.org/wikipedia/en/f/f1/Burger_King_logo_%282020%29.svg",
      cuisines: ["Burgers", "Fast Food", "Beverages"],
      avgRating: "4.3",
      costForTwo: 35000,
      deliveryTime: 20,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "107",
      name: "Biryani Blues",
      imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
      cuisines: ["Biryani", "North Indian", "Mughlai"],
      avgRating: "4.5",
      costForTwo: 45000,
      deliveryTime: 40,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "108",
      name: "Fassos",
      imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400",
      cuisines: ["Rolls", "Wraps", "Biryani", "Fast Food"],
      avgRating: "3.7",
      costForTwo: 20000,
      deliveryTime: 32,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "109",
      name: "Haldiram's",
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400",
      cuisines: ["North Indian", "South Indian", "Sweets"],
      avgRating: "4.4",
      costForTwo: 30000,
      deliveryTime: 35,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "110",
      name: "Barbeque Nation",
      imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400",
      cuisines: ["North Indian", "Barbeque", "Kebabs"],
      avgRating: "4.6",
      costForTwo: 80000,
      deliveryTime: 45,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "111",
      name: "China Town",
      imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400",
      cuisines: ["Chinese", "Asian", "Thai"],
      avgRating: "3.9",
      costForTwo: 40000,
      deliveryTime: 38,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "112",
      name: "Wow! Momo",
      imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400",
      cuisines: ["Momos", "Tibetan", "Fast Food"],
      avgRating: "4.0",
      costForTwo: 20000,
      deliveryTime: 28,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "113",
      name: "Paradise Biryani",
      imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400",
      cuisines: ["Biryani", "Kebabs", "Hyderabadi"],
      avgRating: "4.7",
      costForTwo: 50000,
      deliveryTime: 42,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "114",
      name: "Theobroma",
      imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
      cuisines: ["Bakery", "Desserts", "Cakes"],
      avgRating: "4.5",
      costForTwo: 45000,
      deliveryTime: 30,
    },
  },
  {
    type: "restaurant",
    data: {
      id: "115",
      name: "Naturals Ice Cream",
      imageUrl: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400",
      cuisines: ["Ice Cream", "Desserts", "Beverages"],
      avgRating: "4.8",
      costForTwo: 15000,
      deliveryTime: 20,
    },
  },
];
export default resList;